name: Static Haskell Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lispandfound/ghc-alpine:9.10.2

    steps:
      - uses: actions/checkout@v4

      - name: Update to latest Hackage package list
        run: cabal update

      - name: Build static executable
        run: |
          cabal install \
            --enable-executable-static \
            --enable-split-sections \
            --enable-executable-stripping \
            --installdir=out \
            --overwrite-policy=always \
            --install-method=copy

      - name: Compress binary
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mkdir dist
          tar -cJvf slew-${VERSION}.tar.xz -C out slew

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: slew-${{ github.ref_name }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
